"""Seed terms for bootstrapping the Lexicon vault.

Each dict maps to write_term() parameters. Categories use the vault writer's
VALID_CATEGORIES so files get correct frontmatter.

Mapping from conceptual grouping to writer categories:
  llm          -> llm-foundations
  agents       -> agents
  system-design -> design-patterns
  mlops        -> evals-and-quality  (closest match for ML operations)
  infra        -> infra-and-serving
"""

from __future__ import annotations

SEED_TERMS: list[dict] = [
    # ── LLM (llm-foundations) ─────────────────────────────────────────
    {
        "term": "RAG",
        "full_form": "Retrieval-Augmented Generation",
        "definition": "A technique that augments LLM generation by first retrieving relevant documents from an external knowledge base, grounding responses in factual, up-to-date information.",
        "use_in_sentence": "We added a RAG pipeline so the chatbot could answer questions using our internal documentation instead of relying solely on its training data.",
        "category": "llm-foundations",
        "difficulty": "intermediate",
        "related_terms": ["embeddings", "vector database", "context window"],
        "context_tags": ["retrieval", "knowledge-grounding", "search"],
    },
    {
        "term": "Fine-tuning",
        "full_form": None,
        "definition": "The process of continuing to train a pre-trained model on a smaller, task-specific dataset to adapt its behavior for a particular domain or use case.",
        "use_in_sentence": "After fine-tuning GPT on our customer-support transcripts, the model started generating responses that matched our brand voice.",
        "category": "llm-foundations",
        "difficulty": "intermediate",
        "related_terms": ["transfer learning", "LoRA", "RLHF"],
        "context_tags": ["training", "customization", "domain-adaptation"],
    },
    {
        "term": "RLHF",
        "full_form": "Reinforcement Learning from Human Feedback",
        "definition": "A training technique where a reward model trained on human preference data is used to fine-tune an LLM via reinforcement learning, aligning outputs with human expectations.",
        "use_in_sentence": "RLHF was a key ingredient in making ChatGPT responses more helpful and less harmful compared to the base model.",
        "category": "llm-foundations",
        "difficulty": "advanced",
        "related_terms": ["fine-tuning", "reward model", "PPO", "DPO"],
        "context_tags": ["alignment", "training", "safety"],
    },
    {
        "term": "Prompt Engineering",
        "full_form": None,
        "definition": "The practice of designing and iterating on input prompts to elicit desired behavior from a language model, including techniques like few-shot examples and system instructions.",
        "use_in_sentence": "Good prompt engineering turned a generic model into a reliable JSON extractor without any fine-tuning.",
        "category": "llm-foundations",
        "difficulty": "beginner",
        "related_terms": ["few-shot learning", "chain of thought", "system prompt"],
        "context_tags": ["prompting", "inference", "ux"],
    },
    {
        "term": "Tokenization",
        "full_form": None,
        "definition": "The process of splitting text into smaller units (tokens) that a language model can process, where tokens may be words, sub-words, or individual characters depending on the tokenizer.",
        "use_in_sentence": "Understanding tokenization helped us realize why our API costs were higher than expected — the model was consuming more tokens than the word count suggested.",
        "category": "llm-foundations",
        "difficulty": "beginner",
        "related_terms": ["BPE", "context window", "vocabulary"],
        "context_tags": ["preprocessing", "encoding", "cost"],
    },
    {
        "term": "Attention Mechanism",
        "full_form": None,
        "definition": "A neural network component that allows the model to weigh the relevance of different input tokens when producing each output token, enabling it to focus on the most pertinent parts of the input.",
        "use_in_sentence": "The attention mechanism is what lets a transformer understand that 'it' in the second sentence refers to the 'server' mentioned earlier.",
        "category": "llm-foundations",
        "difficulty": "intermediate",
        "related_terms": ["transformer", "self-attention", "multi-head attention"],
        "context_tags": ["architecture", "neural-networks", "deep-learning"],
    },
    {
        "term": "Transformer",
        "full_form": None,
        "definition": "A neural network architecture based entirely on self-attention mechanisms, replacing recurrence and convolutions, and serving as the foundation for modern LLMs like GPT and BERT.",
        "use_in_sentence": "The transformer architecture's ability to parallelize training across tokens is a major reason why modern LLMs can be trained on massive datasets efficiently.",
        "category": "llm-foundations",
        "difficulty": "intermediate",
        "related_terms": ["attention mechanism", "encoder-decoder", "positional encoding"],
        "context_tags": ["architecture", "deep-learning", "foundation"],
    },
    {
        "term": "Embeddings",
        "full_form": None,
        "definition": "Dense vector representations of text (words, sentences, or documents) in a continuous vector space where semantic similarity corresponds to geometric proximity.",
        "use_in_sentence": "We stored embeddings of every support article so we could find the most relevant ones using cosine similarity at query time.",
        "category": "llm-foundations",
        "difficulty": "beginner",
        "related_terms": ["vector database", "cosine similarity", "RAG"],
        "context_tags": ["representation", "search", "similarity"],
    },
    {
        "term": "Context Window",
        "full_form": None,
        "definition": "The maximum number of tokens a language model can process in a single forward pass, encompassing both the input prompt and the generated output.",
        "use_in_sentence": "We had to summarize long documents before sending them to the model because they exceeded the 8k context window.",
        "category": "llm-foundations",
        "difficulty": "beginner",
        "related_terms": ["tokenization", "RAG", "long-context"],
        "context_tags": ["limits", "inference", "architecture"],
    },
    {
        "term": "Few-shot Learning",
        "full_form": None,
        "definition": "A prompting technique where a small number of input-output examples are provided in the prompt to guide the model's behavior on a new task without any parameter updates.",
        "use_in_sentence": "By including three few-shot examples of the desired JSON format, we got the model to reliably produce structured output.",
        "category": "llm-foundations",
        "difficulty": "beginner",
        "related_terms": ["prompt engineering", "zero-shot", "in-context learning"],
        "context_tags": ["prompting", "inference", "examples"],
    },
    # ── Agents ────────────────────────────────────────────────────────
    {
        "term": "Tool Use",
        "full_form": None,
        "definition": "The ability of an LLM agent to invoke external tools (APIs, databases, code interpreters) to perform actions or gather information beyond its training data.",
        "use_in_sentence": "With tool use enabled, the agent could look up real-time stock prices instead of guessing based on stale training data.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["function calling", "agent loop", "MCP"],
        "context_tags": ["agentic", "integration", "actions"],
    },
    {
        "term": "Function Calling",
        "full_form": None,
        "definition": "A structured interface where the LLM outputs a JSON object specifying which function to call and with what arguments, enabling reliable integration with external systems.",
        "use_in_sentence": "OpenAI's function calling feature let us define a schema for our booking API, and the model would emit structured calls instead of free-form text.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["tool use", "JSON schema", "structured output"],
        "context_tags": ["agentic", "structured-output", "api"],
    },
    {
        "term": "Chain of Thought",
        "full_form": None,
        "definition": "A prompting strategy that encourages the model to break down complex reasoning into intermediate steps before arriving at a final answer, improving accuracy on multi-step tasks.",
        "use_in_sentence": "Adding 'let's think step by step' triggered chain of thought reasoning and boosted the model's math accuracy from 60% to 90%.",
        "category": "agents",
        "difficulty": "beginner",
        "related_terms": ["prompt engineering", "ReAct", "reasoning"],
        "context_tags": ["reasoning", "prompting", "accuracy"],
    },
    {
        "term": "ReAct",
        "full_form": "Reasoning and Acting",
        "definition": "An agent framework where the model alternates between reasoning (thinking about what to do) and acting (calling tools or taking actions), using observations to inform the next step.",
        "use_in_sentence": "Our ReAct agent would first reason about which API to call, execute it, observe the result, and then decide whether to call another tool or respond to the user.",
        "category": "agents",
        "difficulty": "advanced",
        "related_terms": ["chain of thought", "agent loop", "tool use"],
        "context_tags": ["agentic", "reasoning", "framework"],
    },
    {
        "term": "Agent Loop",
        "full_form": None,
        "definition": "The iterative cycle in which an AI agent receives input, decides on an action, executes it, observes the result, and repeats until the task is complete or a stopping condition is met.",
        "use_in_sentence": "The agent loop ran for five iterations — searching docs, filtering results, and synthesizing an answer — before returning a confident response.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["ReAct", "tool use", "planning"],
        "context_tags": ["agentic", "control-flow", "architecture"],
    },
    {
        "term": "Multi-agent System",
        "full_form": None,
        "definition": "An architecture where multiple specialized AI agents collaborate, each handling a different subtask or domain, coordinated by an orchestrator or through message passing.",
        "use_in_sentence": "We built a multi-agent system where one agent handled research, another wrote drafts, and a third reviewed for factual accuracy.",
        "category": "agents",
        "difficulty": "advanced",
        "related_terms": ["orchestrator", "agent loop", "agentic workflow"],
        "context_tags": ["agentic", "coordination", "architecture"],
    },
    {
        "term": "Orchestrator",
        "full_form": None,
        "definition": "A central agent or component that coordinates the execution of multiple sub-agents or tasks, deciding which agent to invoke, in what order, and how to combine their outputs.",
        "use_in_sentence": "The orchestrator decided whether to route the user's request to the coding agent or the research agent based on intent classification.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["multi-agent system", "planning", "routing"],
        "context_tags": ["agentic", "coordination", "control-flow"],
    },
    {
        "term": "MCP",
        "full_form": "Model Context Protocol",
        "definition": "An open protocol that standardizes how AI agents connect to external data sources and tools, providing a uniform interface for context retrieval and tool invocation.",
        "use_in_sentence": "By exposing our internal APIs as MCP servers, any compatible AI agent could query our databases without custom integration code.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["tool use", "function calling", "agent loop"],
        "context_tags": ["protocol", "integration", "standards"],
    },
    {
        "term": "Agentic Workflow",
        "full_form": None,
        "definition": "A multi-step AI-driven process where an LLM autonomously plans, executes, and adapts a sequence of actions to accomplish a complex goal with minimal human intervention.",
        "use_in_sentence": "The agentic workflow handled the entire code-review pipeline: cloning the repo, running linters, analyzing diffs, and posting review comments.",
        "category": "agents",
        "difficulty": "intermediate",
        "related_terms": ["agent loop", "planning", "tool use"],
        "context_tags": ["agentic", "automation", "workflow"],
    },
    {
        "term": "Planning",
        "full_form": None,
        "definition": "The capability of an AI agent to decompose a high-level goal into a sequence of sub-tasks, reason about dependencies, and create an execution plan before taking action.",
        "use_in_sentence": "The agent's planning module broke down 'deploy the new feature' into eight ordered sub-tasks including writing tests, creating a PR, and monitoring rollout.",
        "category": "agents",
        "difficulty": "advanced",
        "related_terms": ["chain of thought", "ReAct", "orchestrator"],
        "context_tags": ["agentic", "reasoning", "decomposition"],
    },
    # ── System Design (design-patterns) ──────────────────────────────
    {
        "term": "Microservices",
        "full_form": None,
        "definition": "An architectural style where an application is composed of small, independently deployable services, each owning its own data and communicating over lightweight protocols.",
        "use_in_sentence": "Moving to microservices let the payments team deploy fixes without waiting for a monolith-wide release cycle.",
        "category": "design-patterns",
        "difficulty": "intermediate",
        "related_terms": ["API gateway", "service mesh", "event-driven"],
        "context_tags": ["architecture", "scalability", "deployment"],
    },
    {
        "term": "Event-driven Architecture",
        "full_form": None,
        "definition": "A design pattern where system components communicate by producing and consuming events asynchronously, enabling loose coupling and high scalability.",
        "use_in_sentence": "Switching to event-driven architecture meant the order service could fire an 'OrderPlaced' event and not care which downstream services consumed it.",
        "category": "design-patterns",
        "difficulty": "intermediate",
        "related_terms": ["pub-sub", "CQRS", "message queue"],
        "context_tags": ["architecture", "async", "decoupling"],
    },
    {
        "term": "CQRS",
        "full_form": "Command Query Responsibility Segregation",
        "definition": "A pattern that separates read and write operations into different models, allowing each to be optimized independently for their specific workload characteristics.",
        "use_in_sentence": "CQRS let us use a denormalized read store for fast dashboard queries while keeping the write side normalized for data integrity.",
        "category": "design-patterns",
        "difficulty": "advanced",
        "related_terms": ["event sourcing", "event-driven architecture", "microservices"],
        "context_tags": ["architecture", "patterns", "data"],
    },
    {
        "term": "Load Balancing",
        "full_form": None,
        "definition": "The process of distributing incoming network traffic across multiple servers to ensure no single server is overwhelmed, improving availability and responsiveness.",
        "use_in_sentence": "Adding a load balancer in front of our API servers eliminated the 502 errors we saw during traffic spikes.",
        "category": "design-patterns",
        "difficulty": "beginner",
        "related_terms": ["horizontal scaling", "health checks", "reverse proxy"],
        "context_tags": ["scalability", "reliability", "networking"],
    },
    {
        "term": "Circuit Breaker",
        "full_form": None,
        "definition": "A resilience pattern that detects failures in downstream services and temporarily stops sending requests to them, preventing cascading failures across the system.",
        "use_in_sentence": "The circuit breaker tripped after the third timeout from the payments API, so we returned cached results instead of hanging.",
        "category": "design-patterns",
        "difficulty": "intermediate",
        "related_terms": ["retry", "bulkhead", "fallback"],
        "context_tags": ["resilience", "fault-tolerance", "patterns"],
    },
    {
        "term": "API Gateway",
        "full_form": None,
        "definition": "A server that acts as a single entry point for client requests, routing them to appropriate backend services while handling cross-cutting concerns like authentication, rate limiting, and logging.",
        "use_in_sentence": "The API gateway handled JWT validation and rate limiting so individual microservices didn't need to implement auth logic.",
        "category": "design-patterns",
        "difficulty": "intermediate",
        "related_terms": ["microservices", "load balancing", "reverse proxy"],
        "context_tags": ["architecture", "networking", "security"],
    },
    {
        "term": "Pub-sub",
        "full_form": "Publish-Subscribe",
        "definition": "A messaging pattern where publishers send messages to a topic without knowledge of subscribers, and subscribers receive messages from topics they are interested in, enabling decoupled communication.",
        "use_in_sentence": "Using pub-sub through Kafka meant the analytics service could consume the same user-event stream as the notification service without either knowing about the other.",
        "category": "design-patterns",
        "difficulty": "beginner",
        "related_terms": ["event-driven architecture", "message queue", "Kafka"],
        "context_tags": ["messaging", "decoupling", "async"],
    },
    {
        "term": "Idempotency",
        "full_form": None,
        "definition": "A property of an operation where performing it multiple times produces the same result as performing it once, critical for safe retries in distributed systems.",
        "use_in_sentence": "We made the payment endpoint idempotent using a client-generated request ID, so retries after network timeouts wouldn't double-charge the customer.",
        "category": "design-patterns",
        "difficulty": "intermediate",
        "related_terms": ["retry", "distributed systems", "API design"],
        "context_tags": ["reliability", "api-design", "patterns"],
    },
    {
        "term": "CAP Theorem",
        "full_form": "Consistency, Availability, Partition Tolerance",
        "definition": "A theorem stating that a distributed data store can provide at most two of three guarantees — consistency, availability, and partition tolerance — requiring architects to make explicit trade-offs.",
        "use_in_sentence": "Given the CAP theorem, we chose eventual consistency for our shopping cart service to maintain availability during network partitions.",
        "category": "design-patterns",
        "difficulty": "advanced",
        "related_terms": ["distributed consensus", "eventual consistency", "Paxos"],
        "context_tags": ["distributed-systems", "theory", "trade-offs"],
    },
    {
        "term": "Distributed Consensus",
        "full_form": None,
        "definition": "A protocol by which multiple nodes in a distributed system agree on a single value or state, ensuring consistency even when some nodes fail or messages are delayed.",
        "use_in_sentence": "Raft's distributed consensus algorithm ensures that our metadata cluster always agrees on which node is the leader, even after a crash.",
        "category": "design-patterns",
        "difficulty": "advanced",
        "related_terms": ["CAP theorem", "Raft", "Paxos", "leader election"],
        "context_tags": ["distributed-systems", "algorithms", "reliability"],
    },
    # ── MLOps (evals-and-quality) ────────────────────────────────────
    {
        "term": "Model Serving",
        "full_form": None,
        "definition": "The infrastructure and process of deploying a trained ML model to a production environment where it can receive requests and return predictions at low latency.",
        "use_in_sentence": "We used TorchServe for model serving so we could handle batched inference requests and scale GPU instances independently.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["inference", "model registry", "shadow deployment"],
        "context_tags": ["deployment", "inference", "production"],
    },
    {
        "term": "A/B Testing",
        "full_form": None,
        "definition": "A controlled experiment where two or more variants of a model or feature are served to different user segments simultaneously to measure which performs better on key metrics.",
        "use_in_sentence": "A/B testing the new recommendation model showed a 12% lift in click-through rate compared to the baseline.",
        "category": "evals-and-quality",
        "difficulty": "beginner",
        "related_terms": ["shadow deployment", "experiment tracking", "statistical significance"],
        "context_tags": ["experimentation", "evaluation", "metrics"],
    },
    {
        "term": "Feature Store",
        "full_form": None,
        "definition": "A centralized repository for storing, managing, and serving ML features, ensuring consistency between training and inference pipelines and enabling feature reuse across teams.",
        "use_in_sentence": "The feature store guaranteed that the same user-engagement features used during training were served at inference time, eliminating train-serve skew.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["data drift", "model serving", "feature engineering"],
        "context_tags": ["data", "infrastructure", "ml-pipeline"],
    },
    {
        "term": "Model Registry",
        "full_form": None,
        "definition": "A versioned repository for storing trained model artifacts along with their metadata, metrics, and lineage, enabling reproducible deployments and model governance.",
        "use_in_sentence": "Before deploying to production, every model had to be registered in the model registry with its evaluation metrics and approval status.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["model serving", "experiment tracking", "CI/CD for ML"],
        "context_tags": ["governance", "versioning", "deployment"],
    },
    {
        "term": "Data Drift",
        "full_form": None,
        "definition": "A change in the statistical properties of incoming production data compared to the training data, which can degrade model performance over time if not detected and addressed.",
        "use_in_sentence": "Our monitoring dashboard flagged data drift in the age distribution feature, explaining why the churn model's accuracy had dropped.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["concept drift", "monitoring", "feature store"],
        "context_tags": ["monitoring", "quality", "production"],
    },
    {
        "term": "Experiment Tracking",
        "full_form": None,
        "definition": "The practice of systematically logging hyperparameters, metrics, artifacts, and code versions for each ML training run to enable comparison, reproducibility, and auditability.",
        "use_in_sentence": "MLflow's experiment tracking made it easy to compare 50 training runs and identify which hyperparameter combination produced the best F1 score.",
        "category": "evals-and-quality",
        "difficulty": "beginner",
        "related_terms": ["model registry", "hyperparameter tuning", "reproducibility"],
        "context_tags": ["experimentation", "tooling", "workflow"],
    },
    {
        "term": "CI/CD for ML",
        "full_form": "Continuous Integration / Continuous Deployment for Machine Learning",
        "definition": "An extension of traditional CI/CD practices to ML workflows, automating data validation, model training, evaluation, and deployment whenever code or data changes.",
        "use_in_sentence": "Our CI/CD for ML pipeline automatically retrained the model on new weekly data, ran evaluation benchmarks, and promoted it to production if metrics passed.",
        "category": "evals-and-quality",
        "difficulty": "advanced",
        "related_terms": ["model registry", "experiment tracking", "data validation"],
        "context_tags": ["automation", "deployment", "pipeline"],
    },
    {
        "term": "Shadow Deployment",
        "full_form": None,
        "definition": "A deployment strategy where a new model receives a copy of production traffic and generates predictions without serving them to users, allowing safe comparison against the current model.",
        "use_in_sentence": "We ran a shadow deployment for two weeks to verify the new model's latency and accuracy before switching any real traffic to it.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["A/B testing", "canary deployment", "model serving"],
        "context_tags": ["deployment", "testing", "risk-mitigation"],
    },
    # ── Infra (infra-and-serving) ────────────────────────────────────
    {
        "term": "Kubernetes",
        "full_form": None,
        "definition": "An open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications across clusters of machines.",
        "use_in_sentence": "Kubernetes automatically rescheduled our crashed pods onto healthy nodes, so the outage was resolved before the on-call engineer even woke up.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["Docker", "service mesh", "infrastructure as code"],
        "context_tags": ["orchestration", "containers", "operations"],
    },
    {
        "term": "Docker",
        "full_form": None,
        "definition": "A platform for building, shipping, and running applications inside lightweight, portable containers that package code with all its dependencies for consistent execution across environments.",
        "use_in_sentence": "Packaging the app as a Docker container eliminated the 'works on my machine' problem and made CI builds reproducible.",
        "category": "infra-and-serving",
        "difficulty": "beginner",
        "related_terms": ["Kubernetes", "container registry", "image"],
        "context_tags": ["containers", "packaging", "devops"],
    },
    {
        "term": "Service Mesh",
        "full_form": None,
        "definition": "A dedicated infrastructure layer that handles service-to-service communication in a microservices architecture, providing features like traffic management, observability, and mutual TLS without changing application code.",
        "use_in_sentence": "After deploying Istio as our service mesh, we got request-level metrics and automatic retries between services for free.",
        "category": "infra-and-serving",
        "difficulty": "advanced",
        "related_terms": ["Kubernetes", "microservices", "sidecar proxy"],
        "context_tags": ["networking", "observability", "security"],
    },
    {
        "term": "Observability",
        "full_form": None,
        "definition": "The ability to understand the internal state of a system from its external outputs, typically through three pillars: logs, metrics, and distributed traces.",
        "use_in_sentence": "Good observability meant we could trace a single user request across twelve microservices and pinpoint the slow database query in minutes.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["OpenTelemetry", "distributed tracing", "monitoring"],
        "context_tags": ["monitoring", "debugging", "operations"],
    },
    {
        "term": "OpenTelemetry",
        "full_form": None,
        "definition": "A vendor-neutral open-source framework for generating, collecting, and exporting telemetry data (traces, metrics, logs) from cloud-native applications.",
        "use_in_sentence": "Instrumenting our Python services with OpenTelemetry let us switch from Jaeger to Grafana Tempo without changing application code.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["observability", "distributed tracing", "Prometheus"],
        "context_tags": ["telemetry", "monitoring", "standards"],
    },
    {
        "term": "Rate Limiting",
        "full_form": None,
        "definition": "A technique for controlling the number of requests a client can make to a service within a given time window, protecting against abuse and ensuring fair resource usage.",
        "use_in_sentence": "Rate limiting on the public API prevented a single misbehaving client from overwhelming the service and degrading performance for everyone else.",
        "category": "infra-and-serving",
        "difficulty": "beginner",
        "related_terms": ["API gateway", "throttling", "token bucket"],
        "context_tags": ["security", "reliability", "api-design"],
    },
    {
        "term": "Blue-green Deployment",
        "full_form": None,
        "definition": "A deployment strategy that maintains two identical production environments (blue and green), routing traffic to one while deploying updates to the other, enabling instant rollback by switching traffic back.",
        "use_in_sentence": "Blue-green deployment gave us zero-downtime releases — if the new version had issues, we just flipped the load balancer back to the old environment.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["canary deployment", "rolling update", "load balancing"],
        "context_tags": ["deployment", "reliability", "devops"],
    },
    {
        "term": "Infrastructure as Code",
        "full_form": None,
        "definition": "The practice of managing and provisioning infrastructure through machine-readable configuration files rather than manual processes, enabling version control, review, and reproducibility.",
        "use_in_sentence": "With infrastructure as code via Terraform, spinning up a staging environment identical to production took a single command instead of a week of manual setup.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["Terraform", "Kubernetes", "GitOps"],
        "context_tags": ["devops", "automation", "provisioning"],
    },
    {
        "term": "Canary Deployment",
        "full_form": None,
        "definition": "A deployment strategy where a new version is gradually rolled out to a small percentage of traffic first, allowing teams to detect issues before exposing all users.",
        "use_in_sentence": "We started with a 5% canary deployment and monitored error rates for an hour before ramping up to full traffic.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["blue-green deployment", "rolling update", "feature flags"],
        "context_tags": ["deployment", "risk-mitigation", "devops"],
    },
    {
        "term": "GitOps",
        "full_form": None,
        "definition": "An operational framework where the desired state of infrastructure and applications is declared in a Git repository, and automated agents ensure the live system matches that state.",
        "use_in_sentence": "With GitOps, merging a PR to the infrastructure repo automatically triggered ArgoCD to reconcile the Kubernetes cluster to the new desired state.",
        "category": "infra-and-serving",
        "difficulty": "intermediate",
        "related_terms": ["infrastructure as code", "Kubernetes", "ArgoCD"],
        "context_tags": ["devops", "automation", "deployment"],
    },
    # ── Additional MLOps ─────────────────────────────────────────────
    {
        "term": "Data Validation",
        "full_form": None,
        "definition": "The process of automatically checking incoming data against expected schemas, distributions, and constraints before it enters an ML pipeline, catching data quality issues early.",
        "use_in_sentence": "Great Expectations ran data validation checks on every new batch, blocking the training pipeline when a column's null rate exceeded 5%.",
        "category": "evals-and-quality",
        "difficulty": "beginner",
        "related_terms": ["data drift", "feature store", "CI/CD for ML"],
        "context_tags": ["data-quality", "pipeline", "automation"],
    },
    {
        "term": "Model Monitoring",
        "full_form": None,
        "definition": "The continuous tracking of a deployed model's performance, latency, and input distributions in production to detect degradation, drift, or anomalies in real time.",
        "use_in_sentence": "Model monitoring alerted us that prediction confidence had dropped 15% overnight, which turned out to be caused by a schema change in the upstream data feed.",
        "category": "evals-and-quality",
        "difficulty": "intermediate",
        "related_terms": ["data drift", "observability", "A/B testing"],
        "context_tags": ["production", "monitoring", "alerting"],
    },
]
